### ISSUE TITLE
v10 compatibility? Players unable to change inventory

### ISSUE THREAD

**Issue by bhi-elliot** [teroparvinen/foundry-party-inventory#15]
Good day,
Thank you for this module.
After updating to v10 of Foundry, the players are now unable to change inventory or currency. As DM, I am able to, but my players cannot.
Unfortunately, I do not have a specific error message to share.

I hope this can get updated and that is it easy for you.
Good luck!
Thank you!

**Comment by GCSmith-07** [comment]
Same issue here

**Comment by bhi-elliot** [comment]
Good day,
I just tried this and it still does not work.
As of version 10.1
GM is able to change inventory and add items.
Players are not.

**Comment by teroparvinen** [comment]
Everything is working properly on my end, so I'm not sure where the problem is.

Make sure you have the dnd5e system and Foundry itself updated and try it with all other modules disabled. Also check the error console for any errors, including on the connecting player browser and include the errors if you run into any.

**Comment by bhi-elliot** [comment]
Hello,
After today's Foundry update (10.291), things seem to be working as intended.
I'm not sure what the change was. In any case, thank you!
